sudo: required
services:
  - docker

before_install:
  - docker build -t abdessamadrajd/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true abdessamadrajd/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-app"
  env: "Dockerenv"
  bucket_name: "elasticbeanstalk-ap-south-1-722066113941"
  bucket_path: "docker-app"
  access_key_id: "AKIA2QHT6QWK3GEGOXNT"
  secret_access_key:
    secure: "70\+acwFYTTloUmFglozZ2WnREvPm5BdexrqJTMX3"
on:
  branch: master