sudo: required
services:
    - docker

before_install:
    - docker build -t abdessamadrajd/react-app -f Dockerfile.dev .
    
script: 
    - docker run abdessamadrajd/react-app npm run test -- --coverage